# cache-bust: 54b4368
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    location /politica-de-privacidade { try_files /index.html =404; }
    location /termos-de-uso { try_files /index.html =404; }
    location /politica-de-cookies { try_files /index.html =404; }
    location /conformidade-lgpd { try_files /index.html =404; }
    location /acessibilidade { try_files /index.html =404; }
    location /dpa { try_files /index.html =404; }
    location /missao-visao-valores { try_files /index.html =404; }
    location / { try_files $uri $uri/ /index.html; }
}
